style: update readme
MapColonies/file-syncer pull request #14
Opened 2023-06-29 14:56 UTC by ronnahom96

| Question                | Answer                                                                          |
| ---------------- | -------------------------------------------------------------------------- |
| Bug fix         | ✖                                                                        |
| New feature     | ✖                                                                        |
| Breaking change | ✖                                                                        |
| Deprecations    | ✖                                                                        |
| Documentation   | ✔                                                                        |
| Tests added     | ✖                                                                        |
| Chore            | ✔                                                                       |

Update readme

2023-07-02 04:57 UTC, netanelC reviewed
Is it merged with the master branch?

2023-07-02 08:56 UTC, netanelC requested changes
Please add dependencies such as job-manager and heartbeat

2023-07-02 11:47 UTC, ronnahom96 commented
> Please add dependencies such as job-manager and heartbeat

done

2023-07-03 10:21 UTC, netanelC approved these changes

2023-07-03 11:27 UTC, merged